project:
  type: website

website:
  title: "Intro to LLMs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor:
  render-on-save: true

brand: _brand.yml
