project:
  type: website
  preview:
    port: 9708
    watch-inputs: true
  render:
    - "./*.qmd"
    - "slides/*.qmd"
  resources:
    - slides

website:
  title: "Intro to LLMs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd

    right:
      - href: references.qmd
      - icon: github
        href: https://github.com/chendaniely/2025-06-05-llm

  page-footer: |
    <a href="https://github.com/chendaniely/2025-06-05-llm">chendaniely/2025-06-05-llm</a>

  repo-url: https://github.com/chendaniely/2025-06-05-llm
  repo-subdir: website
  repo-actions: [edit, issue]

  sidebar:
    - style: docked
      type: light
      background: light
      foreground: dark
      contents:
      - href: 010-welcome.qmd
      - href: 020-anatomy.qmd
      - href: 030-first.qmd
      - href: 040-models.qmd
      - href: 050-chatbot.qmd
      - href: 090-more.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-expand: 2


editor:
  render-on-save: true


brand: _brand.yml
